#!/usr/bin/env python3
"""Continue paper figure style-preview regeneration after summary, using saved outputs where possible."""
from __future__ import annotations

import json
from pathlib import Path
import shutil

import tmp_generate_paper_figures_style_preview as gen


def link_or_copy(src: Path, dst: Path) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    if dst.exists() or dst.is_symlink():
        dst.unlink()
    try:
        dst.symlink_to(src.resolve())
    except OSError:
        shutil.copy2(src, dst)


def main() -> int:
    gen.require_paths([
        gen.STYLE_CONFIG,
        gen.PROP_PARQUET,
        gen.CLIENT_PARQUET,
        gen.PROP_IT_PARQUET,
        gen.CLIENT_IT_PARQUET,
        gen.PROP_DICT,
        gen.CLIENT_DICT,
        gen.OVERLAP_FEATURES,
    ])
    gen.PAPER_IMAGES.mkdir(parents=True, exist_ok=True)
    gen.TMP_CFG_DIR.mkdir(parents=True, exist_ok=True)
    gen.TMP_OUT_DIR.mkdir(parents=True, exist_ok=True)
    gen.TMP_META_OUT.mkdir(parents=True, exist_ok=True)
    for src in [gen.PROP_PARQUET, gen.CLIENT_PARQUET, gen.PROP_IT_PARQUET, gen.CLIENT_IT_PARQUET]:
        gen.symlink_input(src, gen.TMP_META_OUT)

    manifest = {
        "created_at": gen.TIMESTAMP,
        "mode": "continuation_from_distributions_onward",
        "paper_images": str(gen.PAPER_IMAGES),
        "style_config": str(gen.STYLE_CONFIG),
        "preview_root": str(gen.PREVIEW_ROOT),
        "note": "Member statistics and summary were generated by the previous run; this continuation starts at distributions and uses load-only where available.",
        "disabled": {
            "distributions": "--load from saved fit_summary/plot_data; no tail-fit/bootstrap recomputation",
            "execution_schedule_bootstrap": 0,
            "impact_overlay_retention_bootstrap": False,
            "metaorders_compute": {"RUN_METAORDER_COMPUTATION": False, "RUN_SQL_FITS": False},
            "crowding_daily_bootstrap": 0,
            "crowding_eta_bootstrap_permutation_regressions": "0 / 0 / false",
            "crowding_impact_bootstrap_regressions": "0 / false",
            "member_overlap_bootstrap": 0,
        },
    }
    gen.PREVIEW_ROOT.mkdir(parents=True, exist_ok=True)
    (gen.PREVIEW_ROOT / "continuation_manifest.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"[manifest] {gen.PREVIEW_ROOT / 'continuation_manifest.json'}")

    # 3. Metaorder distributions from saved fit/plot-data artifacts only.
    canonical_dist = gen.CANONICAL_OUT / "member_metaorder_distributions"
    dist_load_out = gen.TMP_OUT_DIR / "distributions_load"
    dist_load_artifacts = dist_load_out / "member_metaorder_distributions"
    for name in [
        "metaorder_distribution_fit_summary_prop_vs_client.parquet",
        "metaorder_distribution_fit_summary_prop_vs_client.csv",
        "metaorder_distribution_plot_data_prop_vs_client.parquet",
        "metaorder_distribution_plot_data_prop_vs_client.csv",
    ]:
        link_or_copy(canonical_dist / name, dist_load_artifacts / name)
    dist_cfg = gen.write_temp_config(
        gen.REPO / "config_ymls" / "metaorder_distributions.yml",
        {
            "DATASET_NAME": gen.DATASET,
            "OUTPUT_FILE_PATH": str(dist_load_out),
            "IMG_OUTPUT_PATH": str(gen.PAPER_IMAGES),
            "MEMBER_NATIONALITY": None,
            "PROPRIETARY_DICT_PATH": str(gen.PROP_DICT),
            "CLIENT_DICT_PATH": str(gen.CLIENT_DICT),
            "POWERLAW_FULL_BOOTSTRAP_ENABLED": False,
            "POWERLAW_FULL_BOOTSTRAP_RUNS": 0,
            "POWERLAW_FIT_MAX_WORKERS": 1,
        },
        "metaorder_distributions_load_only.yml",
    )
    gen.run(
        "metaorder_distributions_load_only",
        [gen.PY, "scripts/run_analysis.py", "metaorders", "distributions", "--load"],
        env_updates={"METAORDER_DISTRIBUTIONS_CONFIG": str(dist_cfg)},
    )

    # 4. Execution schedule, inference/bootstrap disabled.
    sched_cfg = gen.write_temp_config(
        gen.REPO / "config_ymls" / "metaorder_execution_schedule.yml",
        {
            "DATASET_NAME": gen.DATASET,
            "OUTPUT_FILE_PATH": str(gen.TMP_OUT_DIR / "execution_schedule"),
            "IMG_OUTPUT_PATH": str(gen.PAPER_IMAGES),
            "MEMBER_NATIONALITY": None,
            "PROPRIETARY_PATH": str(gen.PROP_PARQUET),
            "CLIENT_PATH": str(gen.CLIENT_PARQUET),
            "RUN_EXECUTION_SCHEDULE_INFERENCE": False,
            "BOOTSTRAP_RUNS": 0,
        },
        "metaorder_execution_schedule.yml",
    )
    gen.run(
        "execution_schedule_no_inference",
        [gen.PY, "scripts/run_analysis.py", "execution", "schedule"],
        env_updates={"METAORDER_EXECUTION_SCHEDULE_CONFIG": str(sched_cfg)},
    )

    # 5. Proprietary vs client impact overlays, retention bootstrap disabled.
    overlay_cfg = gen.write_temp_config(
        gen.REPO / "config_ymls" / "plot_prop_nonprop_fits.yml",
        {
            "DATASET_NAME": gen.DATASET,
            "OUTPUT_FILE_PATH": str(gen.TMP_OUT_DIR / "impact_overlay"),
            "IMG_OUTPUT_PATH": str(gen.PAPER_IMAGES),
            "PROPRIETARY_PATH": str(gen.PROP_PARQUET),
            "CLIENT_PATH": str(gen.CLIENT_PARQUET),
            "RUN_RETENTION_BOOTSTRAP": False,
            "RETENTION_BOOTSTRAP_RUNS": 0,
            **gen.STYLE_UPDATES,
        },
        "plot_prop_nonprop_fits.yml",
    )
    gen.run(
        "impact_overlay_no_retention_bootstrap",
        [gen.PY, "scripts/run_analysis.py", "impact", "overlay"],
        env_updates={"PLOT_PROP_NONPROP_FITS_CONFIG": str(overlay_cfg)},
    )

    # 6. Impact fit/surface/path figures from existing filtered parquets only.
    for nationality in [None, "it"]:
        tag = "all" if nationality is None else nationality
        for proprietary in [True, False]:
            group = "proprietary" if proprietary else "client"
            for split_by_side in [False, True]:
                split_tag = "by_side" if split_by_side else "primary"
                compute_cfg = gen.write_temp_config(
                    gen.REPO / "config_ymls" / "metaorder_computation.yml",
                    {
                        "DATASET_NAME": gen.DATASET,
                        "OUTPUT_FILE_PATH": str(gen.TMP_META_OUT),
                        "IMG_OUTPUT_PATH": str(gen.PAPER_IMAGES),
                        "PROPRIETARY": proprietary,
                        "MEMBER_NATIONALITY": nationality,
                        "RUN_INTRO": False,
                        "RUN_METAORDER_COMPUTATION": False,
                        "RUN_SQL_FITS": False,
                        "RUN_WLS": True,
                        "RUN_IMPACT_PATH_PLOT": True,
                        "RUN_SIGNATURE_PLOTS": False,
                        "SPLIT_BY_SIDE": split_by_side,
                        "COMPUTE_EXECUTION_SCHEDULES": False,
                        **gen.STYLE_UPDATES,
                    },
                    f"metaorder_compute_{tag}_{group}_{split_tag}.yml",
                )
                gen.run(
                    f"impact_{tag}_{group}_{split_tag}_existing_tables",
                    [gen.PY, "scripts/run_analysis.py", "metaorders", "compute"],
                    env_updates={"METAORDER_COMP_CONFIG": str(compute_cfg)},
                )

    # 7. Daily/cross/all/member crowding figures: bootstrap/permutation and integrated eta disabled.
    crowd_daily_cfg = gen.write_temp_config(
        gen.REPO / "config_ymls" / "crowding_analysis.yml",
        {
            "DATASET_NAME": gen.DATASET,
            "OUTPUT_FILE_PATH": str(gen.TMP_OUT_DIR / "crowding_daily"),
            "IMG_OUTPUT_PATH": str(gen.PAPER_IMAGES),
            "PROP_PATH": str(gen.PROP_PARQUET),
            "CLIENT_PATH": str(gen.CLIENT_PARQUET),
            "BOOTSTRAP_RUNS": 0,
            "BOOTSTRAP_HEATMAP": False,
            "ACF_BOOTSTRAP_SAMPLES": 0,
            "ATTACH_DAILY_RETURNS": False,
            "PLOT_IMBALANCE_VS_RETURNS": False,
            "ACF_IMBALANCE": False,
            "DISTRIBUTIONS_IMBALANCE": False,
            "RUN_CROWDING_VS_PART_RATE": False,
            "CROWDING_VS_PART_RATE_BOOTSTRAP_RUNS": 0,
            "CROWDING_VS_PART_RATE_CLUSTER_CI": "none",
            "CROWDING_VS_PART_RATE_PERMUTATION_RUNS": 0,
            "CROWDING_VS_PART_RATE_RUN_REGRESSIONS": False,
        },
        "crowding_analysis_daily_no_bootstrap.yml",
    )
    gen.run(
        "crowding_daily_no_bootstrap_no_eta",
        [gen.PY, "scripts/run_analysis.py", "crowding", "daily"],
        env_updates={"CROWDING_CONFIG": str(crowd_daily_cfg)},
    )

    # 8. Crowding vs eta style figures with CI/bootstrap/regression/permutation disabled.
    crowd_eta_cfg = gen.write_temp_config(
        gen.REPO / "config_ymls" / "crowding_analysis.yml",
        {
            "DATASET_NAME": gen.DATASET,
            "OUTPUT_FILE_PATH": str(gen.TMP_OUT_DIR / "crowding_eta"),
            "IMG_OUTPUT_PATH": str(gen.PAPER_IMAGES),
            "PROP_PATH": str(gen.PROP_PARQUET),
            "CLIENT_PATH": str(gen.CLIENT_PARQUET),
            "CROWDING_VS_PART_RATE_BOOTSTRAP_RUNS": 0,
            "CROWDING_VS_PART_RATE_CLUSTER_CI": "none",
            "CROWDING_VS_PART_RATE_PERMUTATION_RUNS": 0,
            "CROWDING_VS_PART_RATE_RUN_REGRESSIONS": False,
        },
        "crowding_analysis_eta_no_bootstrap.yml",
    )
    gen.run(
        "crowding_eta_no_bootstrap_no_permutation",
        [
            gen.PY,
            "scripts/run_analysis.py",
            "crowding",
            "eta",
            "--config-path",
            str(crowd_eta_cfg),
            "--dataset-name",
            gen.DATASET,
            "--prop-path",
            str(gen.PROP_PARQUET),
            "--client-path",
            str(gen.CLIENT_PARQUET),
            "--output-file-path",
            str(gen.TMP_OUT_DIR / "crowding_eta"),
            "--img-output-path",
            str(gen.PAPER_IMAGES),
            "--analysis-tag",
            "crowding_vs_part_rate",
            "--bootstrap-runs",
            "0",
            "--cluster-ci",
            "none",
            "--permutation-runs",
            "0",
            "--no-run-regressions",
            "--plots",
            "plotly",
        ],
    )

    # 9. Crowding-conditioned impact figures with bootstrap/regressions disabled.
    crowd_impact_cfg = gen.write_temp_config(
        gen.REPO / "config_ymls" / "crowding_impact_analysis.yml",
        {
            "DATASET_NAME": gen.DATASET,
            "OUTPUT_FILE_PATH": str(gen.TMP_OUT_DIR / "crowding_impact"),
            "IMG_OUTPUT_PATH": str(gen.PAPER_IMAGES),
            "PROP_PATH": str(gen.PROP_PARQUET),
            "CLIENT_PATH": str(gen.CLIENT_PARQUET),
            "BOOTSTRAP_RUNS": 0,
            "RUN_JOINT_BIN_REGRESSION": False,
            "RUN_POOLED_LOG_REGRESSION": False,
            "SHOW_PROGRESS": False,
            **gen.STYLE_UPDATES,
        },
        "crowding_impact_analysis_no_bootstrap.yml",
    )
    gen.run(
        "crowding_impact_no_bootstrap_no_regression",
        [
            gen.PY,
            "scripts/run_analysis.py",
            "crowding",
            "impact",
            "--config-path",
            str(crowd_impact_cfg),
            "--dataset-name",
            gen.DATASET,
            "--prop-path",
            str(gen.PROP_PARQUET),
            "--client-path",
            str(gen.CLIENT_PARQUET),
            "--output-file-path",
            str(gen.TMP_OUT_DIR / "crowding_impact"),
            "--img-output-path",
            str(gen.PAPER_IMAGES),
            "--analysis-tag",
            "crowding_impact",
            "--bootstrap-runs",
            "0",
            "--no-joint-regression",
            "--no-pooled-log-regression",
            "--no-progress",
            "--write-html",
            "--write-png",
        ],
    )

    # 10. Member active-overlap figures from existing overlap_features.parquet only.
    member_overlap_cfg = gen.write_temp_config(
        gen.REPO / "config_ymls" / "member_active_overlap_crowding.yml",
        {
            "DATASET_NAME": gen.DATASET,
            "OUTPUT_FILE_PATH": str(gen.TMP_OUT_DIR / "member_active_overlap"),
            "IMG_OUTPUT_PATH": str(gen.PAPER_IMAGES),
            "INPUT_PATH": str(gen.OVERLAP_FEATURES),
            "BOOTSTRAP_RUNS": 0,
            "N_JOBS": 1,
            "WRITE_TARGET_PARQUET": True,
        },
        "member_active_overlap_crowding_no_bootstrap.yml",
    )
    gen.run(
        "member_active_overlap_existing_features_no_bootstrap",
        [
            gen.PY,
            "scripts/run_analysis.py",
            "crowding",
            "member-overlap",
            "--config-path",
            str(member_overlap_cfg),
            "--dataset-name",
            gen.DATASET,
            "--input-path",
            str(gen.OVERLAP_FEATURES),
            "--output-file-path",
            str(gen.TMP_OUT_DIR / "member_active_overlap"),
            "--img-output-path",
            str(gen.PAPER_IMAGES),
            "--analysis-tag",
            "member_active_overlap_crowding",
            "--bootstrap-runs",
            "0",
            "--n-jobs",
            "1",
        ],
    )

    print(f"[done] Continuation completed. Root: {gen.PREVIEW_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
